version: "3.5"

networks:
  db-private-net:
    name: "db-private-net"
    ipam:
      config:
        - subnet: 172.50.0.0/24
  db-public-net:
    name: "db-public-net"
    ipam:
      config:
        - subnet: 172.50.1.0/24

x-container-default: &container_defaults
  restart: always
  image: docker.io/bitnami/mariadb-galera:10.4 # 10.4 works where latest does not... collation?
  env_file: .env
  healthcheck:
    test: ['CMD', '/opt/bitnami/scripts/mariadb-galera/healthcheck.sh']
    interval: 15s
    timeout: 5s
    retries: 6
    
services:

  phpmyadmin:
    image: lscr.io/linuxserver/phpmyadmin:latest
    restart: always
    expose:
      - "40002"
    ports:
      - "40002:80"
    environment:
      # - PMA_ARBITRARY=1
      - PMA_HOST=172.50.1.10  # haproxy
      - PMA_PORT=3306
    networks:
      db-public-net:
        ipv4_address: 172.50.1.100

  haproxy:
    image: bitnami/haproxy:latest
    restart: always
    networks:
      db-private-net:
        ipv4_address: 172.50.0.3
      db-public-net:
        ipv4_address: 172.50.1.10
    ports:
      - "3306:3306" # for local operations
    volumes:
      - ./haproxy.cfg:/bitnami/haproxy/conf/haproxy.cfg

  master:
    <<: *container_defaults
    networks:
      db-private-net:
        ipv4_address: 172.50.0.10
    ports:
      - "3307:3306"
    volumes:
      # - './init.sql:/docker-entrypoint-startdb.d/init.sql' # init sql (only uncomment first start)
      - 'mariadb_galera_master:/bitnami/mariadb'
    environment:
      # - MARIADB_DEFAULT_COLLATE="utf8mb4_unicode_ci"
      # - MARIADB_DEFAULT_CHARACTER_SET="utf8mb4"
      - MARIADB_EXTRA_FLAGS=--report-host=master --proxy-protocol-networks=172.50.0.3/32
      - MARIADB_GALERA_CLUSTER_BOOTSTRAP=yes
      - MARIADB_GALERA_FORCE_SAFETOBOOTSTRAP=yes
      - MARIADB_GALERA_CLUSTER_ADDRESS=gcomm://172.50.0.10,172.50.0.11,172.50.0.12,172.50.0.13

  node1:
    <<: *container_defaults
    depends_on:
      - master
    networks:
      db-private-net:
        ipv4_address: 172.50.0.11
    volumes:
      - 'mariadb_galera_node1:/bitnami/mariadb'
    environment:
      # - MARIADB_DEFAULT_COLLATE="utf8mb4_unicode_ci"
      # - MARIADB_DEFAULT_CHARACTER_SET="utf8mb4"
      - MARIADB_EXTRA_FLAGS=--report-host=node1 --proxy-protocol-networks=172.50.0.3/32
      - MARIADB_GALERA_CLUSTER_ADDRESS=gcomm://172.50.0.10,172.50.0.11,172.50.0.12,172.50.0.13
      - MARIADB_GALERA_NODE_ADDRESS=172.50.0.11

  node2:
    <<: *container_defaults
    depends_on:
      - master
    networks:
      db-private-net:
        ipv4_address: 172.50.0.12
    volumes:
      - 'mariadb_galera_node2:/bitnami/mariadb'
    environment:
      # - MARIADB_DEFAULT_COLLATE="utf8mb4_unicode_ci"
      # - MARIADB_DEFAULT_CHARACTER_SET="utf8mb4"
      - MARIADB_EXTRA_FLAGS=--report-host=node2 --proxy-protocol-networks=172.50.0.3/32
      - MARIADB_GALERA_CLUSTER_ADDRESS=gcomm://172.50.0.10,172.50.0.11,172.50.0.12,172.50.0.13
      - MARIADB_GALERA_NODE_ADDRESS=172.50.0.12

  node3:
    <<: *container_defaults
    depends_on:
      - master
    networks:
      db-private-net:
        ipv4_address: 172.50.0.13
    volumes:
      - 'mariadb_galera_node3:/bitnami/mariadb'
    environment:
      # - MARIADB_DEFAULT_COLLATE="utf8mb4_unicode_ci"
      # - MARIADB_DEFAULT_CHARACTER_SET="utf8mb4"
      - MARIADB_EXTRA_FLAGS=--report-host=node3 --proxy-protocol-networks=172.50.0.3/32
      - MARIADB_GALERA_CLUSTER_ADDRESS=gcomm://172.50.0.10,172.50.0.11,172.50.0.12,172.50.0.13
      - MARIADB_GALERA_NODE_ADDRESS=172.50.0.13

volumes:
  mariadb_galera_master:
    driver: local

  mariadb_galera_node1:
    driver: local

  mariadb_galera_node2:
    driver: local

  mariadb_galera_node3:
    driver: local