version: "3.5"

volumes:
  portainer_data:
    name: "portainer_data"

services:

  portainer:
    image: portainer/portainer-ce:latest
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - "portainer_data:/data"
    ports:
      - "9000:9000"
